### ISSUE TITLE
Twitter error response: status code = 405 while running on GitHub Actions

### ISSUE THREAD

**Issue by Saransh-cpp** [tweepy/tweepy#1587]
One of my Twitter bots works completely fine on my machine and Heroku, but today I tried deploying it using GitHub Actions and it keeps throwing this error. Googling the error does provide me with `METHOD_NOT_ALLOWED` text but there are no fixes or answers or articles anywhere. Can someone please help me with this?

Failing GitHub actions  - [here](https://github.com/Saransh-cpp/PyBaMM-Twitter-Bot/actions)

`Python` file from where I am tweeting - [here](https://github.com/Saransh-cpp/PyBaMM-Twitter-Bot/blob/main/tweet_plot.py)

The `.yml` file -
```yml
name: PyBaMM Twitter bot

on:
  push:
    
  pull_request:

  schedule:
    - cron:  '0 3 * * *'

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest wheel coverage
        pip install -r requirements.txt
    
    - name: Run unit tests
      run: |
        python -m unittest
        
    - name: Tweet
      if: matrix.os == 'windows-latest'
      run: |
        python tweet_plot.py
      env:
        ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
        ACCESS_SECRET: ${{ secrets.ACCESS_SECRET }}
        CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
        CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}
    
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    
    - name: Generate coverage report
      if: matrix.os == 'windows-latest'
      run: |
        coverage run -m unittest
    
    - name: Upload coverage to Codecov
      if: matrix.os == 'windows-latest'
      uses: codecov/codecov-action@v1
```

Error - 
```bash
tweepy.error.TweepError: Twitter error response: status code = 405
Error: Process completed with exit code 1.
```
