### ISSUE TITLE
Retreive tweet full text when tweet_mode is extended

### ISSUE THREAD

**Issue by ahuei123456** [tweepy/tweepy#878]
When `tweet_mode` is `extended` twitter api returns full text in `full_text` field instead of `text`. 

https://dev.twitter.com/overview/api/upcoming-changes-to-tweets

**Comment by miketheman** [comment]
The query api will currently allow passing the param to change the returned payload, but the Status result doesn't know how to retrieve the `full_text` field.

```python
new_tweets = client.user_timeline(screen_name=screen_name,
                                      count=200, tweet_mode='extended')
```

```
In [53]: new_tweets[0].full_text is None
Out[53]: False

In [54]: new_tweets[0].text is None
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-54-cff90907e218> in <module>()
----> 1 new_tweets[0].text is None

AttributeError: 'Status' object has no attribute 'text'
```

**Comment by victorpenna** [comment]
I was finding a similar mistake. However I solved my problem, tweet mode = 'extended', only works with tweet.full_text mode.
In the normal method, it will generate the described error.

**Comment by Dmon1Unlimited** [comment]
@victorpenna  hey, could you elaborate on your answer? :) i'm a bit new to this

**Comment by victorpenna** [comment]
has no error, just use do as it says in the documentation. If you are going to use some extra condition, then just use the extra parameters within the condition.

Example:
```
results = api.search(q=query, lang=language, count=tweetCount, tweet_mode='extended')
print(tweet.fulltext)
```
In the above case, I will print according to the arguments, the full mode tweets. But first let me know that I want the tweets in full mode!

**Comment by Rsavreux** [comment]
@victorpenna , I believe tweet.fulltext will generate an error, full_text to be used:

```
results = api.search(q=query, lang=language, count=tweetCount, tweet_mode='extended')
for tweet in results:
        print(tweet.full_text)```

**Comment by spacejunkjim** [comment]
How can I do this with the streaming API?

**Comment by jemshit** [comment]
does not work for user_timeline

**Comment by jaycech3n** [comment]
@spacejunkjim See https://github.com/tweepy/tweepy/issues/935#issuecomment-361416826

**Comment by hugoncosta** [comment]
This doesn't work when the tweet is a retweet. You're forced to make a structure with try/except to look for the full text in the retweet if exists otherwise get the "normal" full text

**Comment by pabblo1717** [comment]
Es verdad el texto completo no aparece si es un retweet.....

**Comment by theAmouie** [comment]
Apparently, tweet_mode='extended' doesn't work for retweets. What should I do to retreive full text of retweets?

**Comment by colditzjb** [comment]
This seems to work for me - getting the most comprehensive text for both streaming and REST API endpoints.  I always connect to REST API with "tweet_mode='extended'", for sure. I think this covers all of the available places where tweet text resides (and gives preference to more comprehensive text)...

```
# This loads the most comprehensive text portion of the tweet  
def parseText(data):       
    # Try for extended text of original tweet, if RT'd (streamer)
    try: text = data['retweeted_status']['extended_tweet']['full_text']
    except: 
        # Try for extended text of an original tweet, if RT'd (REST API)
        try: text = data['retweeted_status']['full_text']
        except:
            # Try for extended text of an original tweet (streamer)
            try: text = data['extended_tweet']['full_text']
            except:
                # Try for extended text of an original tweet (REST API)
                try: text = data['full_text']
                except:
                    # Try for basic text of original tweet if RT'd 
                    try: text = data['retweeted_status']['text']
                    except:
                        # Try for basic text of an original tweet
                        try: text = data['text']
                        except: 
                            # Nothing left to check for
                            text = ''

    text = str(text.encode('unicode-escape'))[2:-1]
    return text
```
